title: Here comes some magic!
author: Lisa Kraineva
email: elizaveta.kraineva@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It's going to be an awesome journey into GitHub Pages.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Lisa-WebDev # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
